dist: trusty
sudo: false
language: node_js
node_js: "8"

notifications:
  webhooks:
    urls:
      - secure: "VMrF0iHhaTi9pliXrBDjKVG8XzpKbrZeyIX1I38+zgWiH0LzoG7ciRVghiAF1grFK1/B8hhplr6vhMVPlxTsIYJQFLIsvbjjnYJmxEYuhODZZPn9trtaEjCwW0wbi0sdEry7bXi2bM2yUqA6Jl9lFeLA2TCudQ4ou5XjATtzMzo="

cache:
  directories:
    - "node_modules"
